#!/bin/bash

cd "${0%/*}"

QUAY_USERNAME=$1
QUAY_PASSWORD=$2
TAG_NAME=$3

echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io

docker build -t quay.io/aerogear/unifiedpush-admin-ui:$TAG_NAME -f ./Dockerfile ../
docker push quay.io/aerogear/unifiedpush-admin-ui:$TAG_NAME